//
//  Helpers+Constants.swift
//  CConnect
//
//  Created by Reo Ogundare on 3/2/25.
//

import SwiftUI

final class Helpers {
    static func currentDateInDateComponents() -> DateComponents {
        return Calendar.current.dateComponents([.day,.month,.year], from: Date())
    }
    static var colors = ["#0077A2":"Celadon Blue",
                         "#CD2504":"Extreme Red ",
                         "#130A06":"Asphalt Black",
                         "#1DB954":"Spotify Green",
                         "#9241C5":"Charming Purple",
                         "#F3BD12":"24K Gold",
                         "#58111A":"Chocolate Cosmos",
                         "#000080":"Digital Navy",
                         "#FD28EC":"Vivid Fuchsia",
                         "#F37507":"Extreme Orange",
                         "#FFFFFF":"White",
                         "#000000":"Black"]
    static let mockAttendees: [String] = [
        "Amanda L",
        "Alex K",
        "Jake M",
        "Erin N",
        "Ronald X",
        "Elizabeth W",
        "Crooks L",
        "Gerald C",
        "Frank K",
        "Daniel F"
    ]
}

extension Helpers {
    static let mockAttendeesUsers: [User] = [
        User(first: "Amanda", last: "Lebowski"),
            User(first: "John", last: "Doe"),
            User(first: "Jane", last: "Smith"),
            User(first: "Peter", last: "Jones"),
            User(first: "Sarah", last: "Connor"),
            User(first: "Michael", last: "Jordan"),
            User(first: "Alice", last: "Wonderland"),
            User(first: "Bob", last: "The Builder"),
            User(first: "Charlie", last: "Chaplin"),
            User(first: "Diana", last: "Prince"),
            User(first: "Emily", last: "Johnson"),
            User(first: "Daniel", last: "Williams"),
            User(first: "Sophia", last: "Brown"),
            User(first: "Oliver", last: "Garcia"),
            User(first: "Ava", last: "Miller"),
            User(first: "William", last: "Davis"),
            User(first: "Isabella", last: "Rodriguez"),
            User(first: "James", last: "Martinez"),
            User(first: "Mia", last: "Hernandez"),
            User(first: "Benjamin", last: "Lopez"),
            User(first: "Charlotte", last: "Gonzalez"),
            User(first: "Lucas", last: "Wilson"),
            User(first: "Amelia", last: "Anderson"),
            User(first: "Henry", last: "Thomas"),
            User(first: "Harper", last: "Taylor"),
            User(first: "Alexander", last: "Moore"),
            User(first: "Evelyn", last: "Jackson"),
            User(first: "Noah", last: "Martin"),
            User(first: "Abigail", last: "Lee"),
            User(first: "Liam", last: "Perez"),
            User(first: "Ella", last: "Thompson"),
            User(first: "Elijah", last: "White"),
            User(first: "Avery", last: "Harris"),
            User(first: "Mason", last: "Sanchez"),
            User(first: "Grace", last: "Clark"),
            User(first: "Ethan", last: "Ramirez"),
            User(first: "Scarlett", last: "Lewis"),
            User(first: "Jacob", last: "Robinson"),
            User(first: "Chloe", last: "Walker"),
            User(first: "Michael", last: "Young"),
            User(first: "Victoria", last: "Allen"),
            User(first: "Logan", last: "King"),
            User(first: "Aria", last: "Wright"),
            User(first: "Jackson", last: "Scott"),
            User(first: "Mila", last: "Torres"),
            User(first: "Samuel", last: "Nguyen"),
            User(first: "Lily", last: "Hill"),
            User(first: "Caleb", last: "Flores"),
            User(first: "Zoey", last: "Green"),
            User(first: "Owen", last: "Adams"),
            User(first: "Layla", last: "Nelson"),
            User(first: "Matthew", last: "Baker"),
            User(first: "Riley", last: "Hall"),
            User(first: "Joseph", last: "Rivera"),
            User(first: "Nora", last: "Campbell"),
            User(first: "Gabriel", last: "Mitchell"),
            User(first: "Eleanor", last: "Carter"),
            User(first: "David", last: "Roberts"),
            User(first: "Madison", last: "Phillips"),
            User(first: "Jonathan", last: "Evans"),
            User(first: "Luna", last: "Turner"),
            User(first: "Andrew", last: "Parker"),
            User(first: "Penelope", last: "Collins"),
            User(first: "Anthony", last: "Edwards"),
            User(first: "Elara", last: "Stewart"),
            User(first: "Dylan", last: "Morris"),
            User(first: "Audrey", last: "Russell"),
            User(first: "Nicholas", last: "Cook"),
            User(first: "Hazel", last: "Morgan"),
            User(first: "Christian", last: "Bell"),
            User(first: "Brooklyn", last: "Murphy"),
            User(first: "Christopher", last: "Bailey"),
            User(first: "Autumn", last: "Cooper"),
            User(first: "Joshua", last: "Rogers"),
            User(first: "Aurora", last: "Reed"),
            User(first: "Ryan", last: "Howard"),
            User(first: "Stella", last: "Cox"),
            User(first: "Nathan", last: "Ward"),
            User(first: "Natalie", last: "Peterson"),
            User(first: "Aaron", last: "Gray"),
            User(first: "Piper", last: "James"),
            User(first: "Connor", last: "Watson"),
            User(first: "Lucy", last: "Brooks"),
            User(first: "Gavin", last: "Kelly"),
            User(first: "Savannah", last: "Sanders"),
            User(first: "Evan", last: "Price"),
            User(first: "Bella", last: "Bennett"),
            User(first: "Adrian", last: "Wood"),
            User(first: "Willow", last: "Barnes"),
            User(first: "Julian", last: "Ross"),
            User(first: "Camila", last: "Henderson"),
            User(first: "Charles", last: "Coleman"),
            User(first: "Paisley", last: "Jenkins"),
            User(first: "Thomas", last: "Perry"),
            User(first: "Ruby", last: "Powell"),
            User(first: "Hunter", last: "Long"),
            User(first: "Valentina", last: "Patterson"),
            User(first: "Robert", last: "Hughes"),
            User(first: "Genesis", last: "Washington"),
            User(first: "Isaac", last: "Butler"),
            User(first: "Kennedy", last: "Fisher"),
            User(first: "Steven", last: "Foster")
    ]
}
